---
- hosts: localhost
  connection: local
  vars:
    dockitems_to_persist:
      - name: Calendar
        path: /Applications/Calendar.app
        pos: 1
      - name: Firefox
        path: "~/Applications/Homebrew Apps/Firefox.app"
        pos: 2
      - name: Emacs
        path: "/Applications/Nix Apps/Emacs.app"
        pos: 3
      - name: kitty
        path: "~/Applications/Home Manager Apps/kitty.app"
        pos: 4
  tasks:
    - name: Clone emacs-config repository into ~/Config
      git:
        repo: https://github.com/mxco86/emacs-config.git
        version: master
        dest: /Users/mryall/Config/emacs-config
        accept_hostkey: yes
      # ssh-agent doesn't allow key to pass through remote sudo commands.
      become: no
    - name: Create symbolic link for .emacs
      file:
        src: /Users/mryall/Config/emacs-config/.emacs
        dest: /Users/mryall/.emacs
        state: link
    - name: Create symbolic link for .emacs.d
      file:
        src: /Users/mryall/Config/emacs-config/.emacs.d
        dest: /Users/mryall/.emacs.d
        state: link
    - name: Remove all items from Dock
      shell: dockutil --remove all --no-restart
    - name: Check if items in dock exist
      shell: dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}' --no-restart
      with_items: "{{dockitems_to_persist}}"
    - name: Fix dock item order
      shell: dockutil --move '{{ item.name }}' --position {{ item.pos }} --no-restart
      with_items: "{{dockitems_to_persist}}"
    - name: Enable SSH 
      shell: sudo launchctl load -w /System/Library/LaunchDaemons/ssh.plist
    - name: Check if homebrew is installed
      stat:
        path: "/usr/local/bin/brew"
      register: "homebrew_check"
    - name: Install Homebrew
      when: homebrew_check == false
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"        
    # Keyboard input config
    # Startup items config - Spectacle
    # Apps - Sonos, Sky Sports
